baseURL = "https://otterable.github.io"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"


# The browser tab name
title = "We've moved :^)"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

   
    
    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
